# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Harvesting Clouds
tagline:          'Everything about Private and Public Clouds'
description:      'Blog about all things regarding private and public clouds. Authored by <a href="https://twitter.com/20aman" target="_blank">@20aman</a>.'
url:              http://HarvestingClouds.com
baseurl:          /

author:
  name:           'Aman Sharma'
  url:            https://twitter.com/20aman

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/HarvestingClouds

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
